version: "3.3"

services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: ft_transcendence_frontend:v1.0.0
        restart: on-failure
        depends_on:
            - backend
        networks:
            - ft_transcendence_network
        ports:
            - "8080:8080"

    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                - POSTGRES_USER
                - POSTGRES_PASSWORD
        image: ft_transcendence_backend:v1.0.0
        restart: on-failure
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        networks:
            - ft_transcendence_network
        ports:
            - "3000:3000"
        extra_hosts:
            - "${DOMAIN_NAME}:${DOMAIN_TARGET}"
            - "www.${DOMAIN_NAME}:${DOMAIN_TARGET}"

    postgres:
        container_name: postgres
        build:
            context: ./postgres
            dockerfile: Dockerfile
            args:
                - POSTGRES_USER
                - POSTGRES_PASSWORD
        image: ft_transcendence_postgres:v1.0.0
        restart: on-failure
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        networks:
            - ft_transcendence_network
        ports:
            - "5432:5432"

networks:
    ft_transcendence_network:
        driver: bridge

volumes:
    postgres-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "${VOLUMES_DIR}/postgres-data"

