version: "3.7"

services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        image: ft_transcendence_frontend:v1.0.0-dev
        restart: on-failure
        depends_on:
            - backend
        networks:
            - project_network-dev
        ports:
            - "8080:8080"
        extra_hosts:
            - "${DOMAIN_NAME}:${DOMAIN_TARGET}"
            - "www.${DOMAIN_NAME}:${DOMAIN_TARGET}"
        volumes:
            - "./backend/app:/root/app"

    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
            args:
                - POSTGRES_USER
                - POSTGRES_PASSWORD
        image: ft_transcendence_backend:v1.0.0-dev
        restart: on-failure
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        networks:
            - project_network-dev
        ports:
            - "3000:3000"
        volumes:
            - "./frontend/app:/root/app"

    postgres:
        container_name: postgres
        build:
            context: ./postgres
            dockerfile: Dockerfile
            args:
                - POSTGRES_USER
                - POSTGRES_PASSWORD
        image: ft_transcendence_postgres:v1.0.0-dev
        restart: on-failure
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        networks:
            - project_network-dev
        ports:
            - "5432:5432"
        volumes:
            - "postgres-dev-data:/var/lib/postgresql/data"

networks:
    project_network-dev:
        driver: bridge

volumes:
    postgres-dev-data:

